### ISSUE TITLE
support to read multiple files in "read_file"

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/buildflow#29]
```yaml
read_file:
  files:
  - name: foo # variable name
    path: foo.txt
```
