### ISSUE TITLE
fix: failed to parge a item in task: cannot convert to object: map[interface {}]interface {}

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/buildflow#81]
Same as #79

```yaml
---
phases:
- name: main
  tasks:
  - name: "list {{.Item.Key}} {{.Item.Value}}"
    input: |
      result := {
        foo: Item.Value
      }
    command:
      command: "echo {{.Item.Key}} {{.Item.Value}}"
    items:
      1:
        foo: foo
      2:
        bar: bar
```

```
ERRO[0000] failed to run an input                        error="cannot convert to object: map[interface {}]interface {}" phase_name=main task_index=0 task_name="list 1 map[foo:foo]"
ERRO[0000] failed to run a task                          error="failed to run an input: cannot convert to object: map[interface {}]interface {}" phase_name=main task_name="list 1 map[foo:foo]"
ERRO[0000] failed to run an input                        error="cannot convert to object: map[interface {}]interface {}" phase_name=main task_index=1 task_name="list 2 map[bar:bar]"
ERRO[0000] failed to run a task                          error="failed to run an input: cannot convert to object: map[interface {}]interface {}" phase_name=main task_name="list 2 map[bar:bar]"
```
