### ISSUE TITLE
support to read JSON

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/buildflow#85]
```yaml
  - name: foo
    read_file:
      path: read_file.json
      format: json
```

```
.Task.File.Data
```
